# Generated by Django 6.0.2 on 2026-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("opis_id", models.IntegerField(db_index=True, help_text="OPIS Truckstop ID")),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=512)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("rack_id", models.IntegerField(blank=True, null=True)),
                (
                    "retail_price",
                    models.FloatField(help_text="Retail fuel price in USD per gallon"),
                ),
                ("latitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("longitude", models.FloatField(blank=True, db_index=True, null=True)),
            ],
            options={
                "ordering": ["state", "city", "retail_price"],
                "indexes": [models.Index(fields=["latitude", "longitude"], name="idx_lat_lon")],
            },
        ),
    ]
